package common

import "real-time-quiz/internal/entity"

var DemoQuestions = []entity.Question{
	{ID: "1", QuizID: "quiz1", Content: "What is the capital of France?", Options: []string{"Paris", "London", "Berlin", "Rome"}, Answer: "Paris"},
	{ID: "2", QuizID: "quiz1", Content: "What is 2 + 2?", Options: []string{"3", "4", "5", "6"}, Answer: "4"},
	{ID: "3", QuizID: "quiz1", Content: "What color is the sky?", Options: []string{"Blue", "Green", "Red", "Yellow"}, Answer: "Blue"},
	{ID: "4", QuizID: "quiz1", Content: "Which planet is known as the Red Planet?", Options: []string{"Earth", "Mars", "Jupiter", "Venus"}, Answer: "Mars"},
	{ID: "5", QuizID: "quiz1", Content: "What is the largest ocean?", Options: []string{"Atlantic", "Indian", "Pacific", "Arctic"}, Answer: "Pacific"},
	{ID: "6", QuizID: "quiz1", Content: "Who wrote 'Romeo and Juliet'?", Options: []string{"Shakespeare", "Dickens", "Hemingway", "Tolkien"}, Answer: "Shakespeare"},
	{ID: "7", QuizID: "quiz1", Content: "What is the boiling point of water?", Options: []string{"90°C", "100°C", "110°C", "120°C"}, Answer: "100°C"},
	{ID: "8", QuizID: "quiz1", Content: "Which animal is known as man's best friend?", Options: []string{"Cat", "Dog", "Horse", "Parrot"}, Answer: "Dog"},
	{ID: "9", QuizID: "quiz1", Content: "What is the largest continent?", Options: []string{"Africa", "Asia", "Europe", "Australia"}, Answer: "Asia"},
	{ID: "10", QuizID: "quiz1", Content: "What is the chemical symbol for gold?", Options: []string{"Au", "Ag", "Gd", "Go"}, Answer: "Au"},
	{ID: "11", QuizID: "quiz1", Content: "How many days in a leap year?", Options: []string{"365", "366", "364", "367"}, Answer: "366"},
	{ID: "12", QuizID: "quiz1", Content: "What is the tallest mountain?", Options: []string{"K2", "Everest", "Fuji", "Alps"}, Answer: "Everest"},
	{ID: "13", QuizID: "quiz1", Content: "Who painted the Mona Lisa?", Options: []string{"Van Gogh", "Da Vinci", "Picasso", "Rembrandt"}, Answer: "Da Vinci"},
	{ID: "14", QuizID: "quiz1", Content: "What is the hardest natural substance?", Options: []string{"Gold", "Iron", "Diamond", "Silver"}, Answer: "Diamond"},
	{ID: "15", QuizID: "quiz1", Content: "Which gas do plants absorb?", Options: []string{"Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"}, Answer: "Carbon Dioxide"},
	{ID: "16", QuizID: "quiz1", Content: "What is the main language of Brazil?", Options: []string{"Spanish", "Portuguese", "French", "English"}, Answer: "Portuguese"},
	{ID: "17", QuizID: "quiz1", Content: "What is the smallest prime number?", Options: []string{"0", "1", "2", "3"}, Answer: "2"},
	{ID: "18", QuizID: "quiz1", Content: "Who discovered gravity?", Options: []string{"Newton", "Einstein", "Galileo", "Tesla"}, Answer: "Newton"},
	{ID: "19", QuizID: "quiz1", Content: "What is the freezing point of water?", Options: []string{"0°C", "32°C", "100°C", "-10°C"}, Answer: "0°C"},
	{ID: "20", QuizID: "quiz1", Content: "Which country is known as the Land of the Rising Sun?", Options: []string{"China", "Japan", "Korea", "Thailand"}, Answer: "Japan"},
	{ID: "21", QuizID: "quiz1", Content: "What is the largest mammal?", Options: []string{"Elephant", "Blue Whale", "Giraffe", "Hippo"}, Answer: "Blue Whale"},
	{ID: "22", QuizID: "quiz1", Content: "What is the square root of 16?", Options: []string{"2", "4", "8", "16"}, Answer: "4"},
	{ID: "23", QuizID: "quiz1", Content: "Who is the author of Harry Potter?", Options: []string{"Rowling", "Tolkien", "Lewis", "Martin"}, Answer: "Rowling"},
	{ID: "24", QuizID: "quiz1", Content: "What is the largest desert?", Options: []string{"Sahara", "Gobi", "Kalahari", "Arctic"}, Answer: "Sahara"},
	{ID: "25", QuizID: "quiz1", Content: "Which element has atomic number 1?", Options: []string{"Oxygen", "Hydrogen", "Helium", "Carbon"}, Answer: "Hydrogen"},
	{ID: "26", QuizID: "quiz1", Content: "What is the main ingredient in bread?", Options: []string{"Rice", "Wheat", "Corn", "Barley"}, Answer: "Wheat"},
	{ID: "27", QuizID: "quiz1", Content: "What is the capital of Italy?", Options: []string{"Rome", "Milan", "Venice", "Naples"}, Answer: "Rome"},
	{ID: "28", QuizID: "quiz1", Content: "Which is the longest river?", Options: []string{"Amazon", "Nile", "Yangtze", "Mississippi"}, Answer: "Nile"},
	{ID: "29", QuizID: "quiz1", Content: "What is the main gas in the air we breathe?", Options: []string{"Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"}, Answer: "Nitrogen"},
	{ID: "30", QuizID: "quiz1", Content: "Who invented the telephone?", Options: []string{"Bell", "Edison", "Tesla", "Newton"}, Answer: "Bell"},
	{ID: "31", QuizID: "quiz1", Content: "What is the capital of Japan?", Options: []string{"Tokyo", "Osaka", "Kyoto", "Nagoya"}, Answer: "Tokyo"},
	{ID: "32", QuizID: "quiz1", Content: "What is the largest bird?", Options: []string{"Eagle", "Ostrich", "Penguin", "Swan"}, Answer: "Ostrich"},
	{ID: "33", QuizID: "quiz1", Content: "What is the chemical symbol for water?", Options: []string{"H2O", "O2", "CO2", "HO"}, Answer: "H2O"},
	{ID: "34", QuizID: "quiz1", Content: "Who was the first man on the moon?", Options: []string{"Armstrong", "Aldrin", "Collins", "Gagarin"}, Answer: "Armstrong"},
	{ID: "35", QuizID: "quiz1", Content: "What is the capital of Germany?", Options: []string{"Berlin", "Munich", "Frankfurt", "Hamburg"}, Answer: "Berlin"},
	{ID: "36", QuizID: "quiz1", Content: "What is the largest planet?", Options: []string{"Earth", "Jupiter", "Saturn", "Mars"}, Answer: "Jupiter"},
	{ID: "37", QuizID: "quiz1", Content: "What is the main ingredient in sushi?", Options: []string{"Rice", "Fish", "Seaweed", "Soy Sauce"}, Answer: "Rice"},
	{ID: "38", QuizID: "quiz1", Content: "What is the capital of Canada?", Options: []string{"Toronto", "Ottawa", "Vancouver", "Montreal"}, Answer: "Ottawa"},
	{ID: "39", QuizID: "quiz1", Content: "What is the smallest country?", Options: []string{"Monaco", "Vatican", "Nauru", "San Marino"}, Answer: "Vatican"},
	{ID: "40", QuizID: "quiz1", Content: "What is the chemical symbol for iron?", Options: []string{"Ir", "Fe", "In", "I"}, Answer: "Fe"},
	{ID: "41", QuizID: "quiz1", Content: "What is the capital of Australia?", Options: []string{"Sydney", "Melbourne", "Canberra", "Perth"}, Answer: "Canberra"},
	{ID: "42", QuizID: "quiz1", Content: "What is the largest island?", Options: []string{"Greenland", "Australia", "Borneo", "Madagascar"}, Answer: "Greenland"},
	{ID: "43", QuizID: "quiz1", Content: "What is the main language of Egypt?", Options: []string{"Arabic", "English", "French", "Spanish"}, Answer: "Arabic"},
	{ID: "44", QuizID: "quiz1", Content: "What is the capital of Russia?", Options: []string{"Moscow", "Saint Petersburg", "Kazan", "Sochi"}, Answer: "Moscow"},
	{ID: "45", QuizID: "quiz1", Content: "What is the largest lake?", Options: []string{"Baikal", "Superior", "Victoria", "Caspian Sea"}, Answer: "Caspian Sea"},
	{ID: "46", QuizID: "quiz1", Content: "What is the main ingredient in guacamole?", Options: []string{"Tomato", "Avocado", "Onion", "Pepper"}, Answer: "Avocado"},
	{ID: "47", QuizID: "quiz1", Content: "What is the capital of Spain?", Options: []string{"Madrid", "Barcelona", "Valencia", "Seville"}, Answer: "Madrid"},
	{ID: "48", QuizID: "quiz1", Content: "What is the largest land animal?", Options: []string{"Elephant", "Rhino", "Hippo", "Giraffe"}, Answer: "Elephant"},
	{ID: "49", QuizID: "quiz1", Content: "What is the main ingredient in hummus?", Options: []string{"Chickpeas", "Lentils", "Beans", "Peas"}, Answer: "Chickpeas"},
	{ID: "50", QuizID: "quiz1", Content: "What is the capital of the USA?", Options: []string{"New York", "Washington D.C.", "Los Angeles", "Chicago"}, Answer: "Washington D.C."},
}
